name: database-compose

services:

  postgresdb:
    container_name: postgresdb-container
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - shared-net
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  dbviewer:
    image: adminer:5.4.1
    container_name: adminer-container
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb-container
      ADMINER_DEFAULT_DRIVER: pgsql
    networks:
      - shared-net
    ports:
      - "9090:8080"

      
volumes:
  postgres_data:
networks:
  shared-net:
    external: true